#!/bin/bash

PROJDIR="/srv/txtadv"
PIDFILE="gunicorn.pid"

cd $PROJDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi

bin/django run_gunicorn 127.0.0.1:10001 -w 5 --pid=$PIDFILE --preload
